/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Bean.DanhMucBean;
import controllers.ThuChiController;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.ScrollPane;
import java.awt.font.TextAttribute;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import views.ThuChiFrame.CacHoNoPhiJFrame;
import views.ThuChiFrame.CacKhoanDongGopJFrame;
import views.ThuChiFrame.NopTienJFrame;
import views.ThuChiFrame.ThemKhoanDongGopJFrame;
import views.ThuChiFrame.XemDuNoJFrame;

/**
 *
 * @author Admin
 */
public class ThuChiPanel extends javax.swing.JPanel {
    private JFrame parentJFrame;
    private ThuChiController thuChiController;
    /**
     * Creates new form ThuChiPanel
     */
    public ThuChiPanel() {
        initComponents();
    }

    public ThuChiPanel(JFrame parentFrame) throws SQLException {
        this.parentJFrame = parentFrame;
        initComponents();
        this.thuChiController = new ThuChiController(this.parentJFrame,this.jScrollPane1);
        this.thuChiController.setData();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        addBtn = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        nhapTienDaThu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        xemDuNo = new javax.swing.JPanel();
        xemDuNolabel = new javax.swing.JLabel();

        setOpaque(false);

        addBtn.setBackground(new java.awt.Color(102, 153, 255));
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBtnMouseExited(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("   Thêm khoản thu");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout addBtnLayout = new javax.swing.GroupLayout(addBtn);
        addBtn.setLayout(addBtnLayout);
        addBtnLayout.setHorizontalGroup(
            addBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        addBtnLayout.setVerticalGroup(
            addBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        nhapTienDaThu.setBackground(new java.awt.Color(102, 153, 255));
        nhapTienDaThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhapTienDaThuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nhapTienDaThuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nhapTienDaThuMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Nhập khoản đã thu");

        javax.swing.GroupLayout nhapTienDaThuLayout = new javax.swing.GroupLayout(nhapTienDaThu);
        nhapTienDaThu.setLayout(nhapTienDaThuLayout);
        nhapTienDaThuLayout.setHorizontalGroup(
            nhapTienDaThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        nhapTienDaThuLayout.setVerticalGroup(
            nhapTienDaThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        xemDuNo.setBackground(new java.awt.Color(102, 153, 255));
        xemDuNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xemDuNoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xemDuNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xemDuNoMouseExited(evt);
            }
        });

        xemDuNolabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xemDuNolabel.setForeground(new java.awt.Color(255, 255, 255));
        xemDuNolabel.setText("Xem danh sách dư nợ theo hộ khẩu");

        javax.swing.GroupLayout xemDuNoLayout = new javax.swing.GroupLayout(xemDuNo);
        xemDuNo.setLayout(xemDuNoLayout);
        xemDuNoLayout.setHorizontalGroup(
            xemDuNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xemDuNoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xemDuNolabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        xemDuNoLayout.setVerticalGroup(
            xemDuNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xemDuNolabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xemDuNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nhapTienDaThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nhapTienDaThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xemDuNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        // TODO add your handling code here:
        ThemKhoanDongGopJFrame themKhoanDongGop = new ThemKhoanDongGopJFrame(this.parentJFrame, this.thuChiController);
        themKhoanDongGop.setLocationRelativeTo(null);
        themKhoanDongGop.setResizable(false);
        themKhoanDongGop.setVisible(true);
    }//GEN-LAST:event_addBtnMouseClicked

    private void addBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseEntered
        this.addBtn.setBackground(new Color(0,51,153));
    }//GEN-LAST:event_addBtnMouseEntered

    private void addBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseExited
        // TODO add your handling code here:
        this.addBtn.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_addBtnMouseExited

    private void nhapTienDaThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhapTienDaThuMouseClicked
        // TODO add your handling code here:
        NopTienJFrame nopTien = new NopTienJFrame(this.parentJFrame, this.thuChiController);
        nopTien.setLocationRelativeTo(null);
        nopTien.setResizable(false);
        nopTien.setVisible(true);
    }//GEN-LAST:event_nhapTienDaThuMouseClicked

    private void nhapTienDaThuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhapTienDaThuMouseEntered
        // TODO add your handling code here:
        this.nhapTienDaThu.setBackground(new Color(0,51,153));
    }//GEN-LAST:event_nhapTienDaThuMouseEntered

    private void nhapTienDaThuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhapTienDaThuMouseExited
        // TODO add your handling code here:
          this.nhapTienDaThu.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_nhapTienDaThuMouseExited

    private void xemDuNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xemDuNoMouseClicked
        // TODO add your handling code here:
        XemDuNoJFrame xemDuNo = new XemDuNoJFrame(this.parentJFrame, this.thuChiController);
        xemDuNo.setLocationRelativeTo(null);
        xemDuNo.setResizable(false);
        xemDuNo.setVisible(true);
    }//GEN-LAST:event_xemDuNoMouseClicked

    private void xemDuNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xemDuNoMouseEntered
        // TODO add your handling code here:
        this.xemDuNo.setBackground(new Color(0,51,153));
    }//GEN-LAST:event_xemDuNoMouseEntered

    private void xemDuNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xemDuNoMouseExited
        // TODO add your handling code here:
        this.xemDuNo.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_xemDuNoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel nhapTienDaThu;
    private javax.swing.JPanel xemDuNo;
    private javax.swing.JLabel xemDuNolabel;
    // End of variables declaration//GEN-END:variables
}
